# ------------------------------------
# Ubuntu/Debian: Install apache and php for Ubuntu
# ------------------------------------
- name: Install Apache and PHP on Ubuntu
  tags: apache,apache2,ubuntu
  ansible.builtin.package:
    name:
      - "{{ apache_package }}"
      - "{{ php_package }}"
    state: latest
  when: ansible_os_family == "Debian"

# ------------------------------------
# Fedora: Install apache and php for Fedora servers
# Fedora: fallback method: using shell to avoid dnf5 bug
# ------------------------------------
- name: Install Apache and PHP on Fedora
  tags: apache,centos,httpd
  ansible.builtin.shell: "dnf install -y {{ apache_package }} {{ php_package }}"
  when: ansible_os_family == "RedHat"

- name: Start httpd (Fedora)
  tags: apache,fedora, httpd
  service: 
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: copy default html file for ansible_ssh_private_key_file
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644